- name: main playbook for blocks rescue always
  hosts: all

  tasks:
    - name: setting up http server
      block:
        - name: installing httpd
          yum:
            name: httpd
            state: present
        - name: restart httpd
          service:
            name: httpd
            state: restarted
          when: ansible_distribution == "RedHat"
