- name: main playbook for restart
  hosts: all

  tasks:

    - name: check if crond is running
      command: /usr/bin/systemctl is-active crond
      ignore_errors: yes
      register: result

    - name: restart ssh only if crond is running
      systemd: 
        name: sshd
        state: restarted
      when: result.rc == 0
