- name: playbook to create a user with encrypted password

  hosts: all

  vars:
    password: "$6$mysecretsalt$qJbapG68nyRab3gxvKWPUcs2g3t0oMHSHMnSKecYNpSi3CuZm.GbBqXO8BE6EI6P1JUefhA0qvD7b5LSh./PU1"

  tasks:

    - name: create user
      user:
        name: anna
        password: "{{ password }}"
