- name: playbook to set up a repository
  hosts: all 
  vars:
    my_package: nmap
  tasks:

    - name: get package facts
      package_facts:
        manager: auto

    - name: show package facts
      debug:
        var: ansible_facts.packages[my_package]
      when: my_package in ansible_facts.packages

    - name: connect to example repo
      yum_repository:
        name: lesson12
        description: "RHCE lab 12 repo"
        file: lesson12
        baseurl: ftp://control.example.com/repo/
        gpgcheck: no

    - name: install package
      yum:
        name: "{{ my_package }}"
        state: present

    - name: update package facts
      package_facts:
        manager: auto

    - name: show package facts
      debug:
        var: ansible_facts.packages[my_package]
      when: my_package in ansible_facts.packages
